openapi: 3.0.1
info:
  title: InstaPlus.Api
  version: '1.0'
paths:
  /banks:
    get:
      tags:
        - Banks
      responses:
        '200':
          description: Success
  /group-order:
    get:
      tags:
        - GroupOrder
      responses:
        '200':
          description: Success
    put:
      tags:
        - GroupOrder
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
  /group-order/{id}:
    get:
      tags:
        - GroupOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    delete:
      tags:
        - GroupOrder
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /order:
    get:
      tags:
        - Order
      responses:
        '200':
          description: Success
    put:
      tags:
        - Order
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
  /order/{id}:
    get:
      tags:
        - Order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /order/{orderId}/link-to:
    post:
      tags:
        - Order
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
        - name: code
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
  /receiving-account:
    get:
      tags:
        - ReceivingAccount
      responses:
        '200':
          description: Success
    put:
      tags:
        - ReceivingAccount
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
  /receiving-account/{id}:
    get:
      tags:
        - ReceivingAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
    delete:
      tags:
        - ReceivingAccount
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /receiving-account/{receivingAccountId}/link-to:
    post:
      tags:
        - ReceivingAccount
      parameters:
        - name: receivingAccountId
          in: path
          required: true
          schema:
            type: string
        - name: code
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Success
  /receiving-account/types:
    get:
      tags:
        - ReceivingAccount
      responses:
        '200':
          description: Success
  /runtime-config:
    post:
      tags:
        - RuntimeConfig
      responses:
        '200':
          description: Success
  /transaction-receipt:
    get:
      tags:
        - TransactionReceipt
      responses:
        '200':
          description: Success
    put:
      tags:
        - TransactionReceipt
      responses:
        '200':
          description: Success
  /transaction-receipt/{reference}:
    get:
      tags:
        - TransactionReceipt
      parameters:
        - name: reference
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
  /transaction-receipt/live:
    get:
      tags:
        - TransactionReceipt
      responses:
        '200':
          description: Success
  /user/login:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
  /user/signup:
    post:
      tags:
        - User
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
  /user/password:
    put:
      tags:
        - User
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
  /webhook/events:
    get:
      tags:
        - Webhook
      responses:
        '200':
          description: Success
  /webhook:
    get:
      tags:
        - Webhook
      responses:
        '200':
          description: Success
    put:
      tags:
        - Webhook
      requestBody:
        content:
          application/json-patch+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          text/json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
          application/*+json:
            schema:
              type: object
              additionalProperties:
                $ref: '#/components/schemas/JToken'
      responses:
        '200':
          description: Success
  /webhook/{id}:
    get:
      tags:
        - Webhook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Webhook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
  /webhook/{id}/logs:
    get:
      tags:
        - Webhook
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
components:
  schemas:
    JToken:
      type: array
      items:
        $ref: '#/components/schemas/JToken'
